export const produtos = [
    {nome: "♠ Ruby Sword ♠", imagem: "https://i.imgur.com/T4qK3wo.jpeg", id: "1", nota: 5, desc: "Ruby Sword evoca uma imagem de intensidade e poder combinados com paixão e energia. Esse é um perfume masculino baseado no naipe de espadas que é ao mesmo tempo forte e vigoroso, perfeito para alguém que deseja transmitir confiança e determinação.", preco: 297},
    {nome: "👑 King's Valor 👑", imagem: "https://i.imgur.com/3aoqklN.png", id: "2", nota: 4, desc: "King's Valor é uma fragrância que encapsula a força e a majestade de um rei. As notas frescas e picantes despertam a sensação de energia e vitalidade , enquanto o coração herbal e amadeirado representa a confiança e a sofisticação. As notas de fundo proporcionam uma base rica e envolvente, tornando este perfume ideal para o homem que é forte, carismático elegante.", preco: 347},
    {nome: "♣️ Mystic Ember ♣️", imagem: "https://i.imgur.com/b7ck4Vx.png", id: "3", nota: 4, desc: "Mystic Ember é um perfume que captura a essência de mistério e profundidade espiritual, combinada com um calor persistente e uma energia latente. É um nome que evoca uma sensação de enigma e paixão duradoura, o perfume masculino perfeito para quem deseja transmitir intensidade e uma presença marcante.", preco: 199},
    {nome: "⚜️ Ace of Mischief ⚜️", imagem: "https://i.imgur.com/njYs1Wn.jpeg", id: "5", nota: 4, desc: "Ace of Mischief é uma fragrância que captura a essência ágil e charmosa do Valete. As notas cítricas e especiadas evocam o espírito jovem, astuto e energético dessa carta, enquanto o coração amadeirado e herbal revela a sofisticação oculta por trãs de sua atitude descomplicada. As notas de fundo trazem uma profundidade refinada, criando uma fragrância ideal para quem é dinâmico, ousado e confiante.", preco: 407},
    {nome: "🃏 Silent Tears 🃏", imagem: "https://i.imgur.com/llh9UYT.jpeg", id: "6", nota: 5, desc: "Silent Tears é uma fragrância melancólica e delicada que reflete a tristeza oculta do Coringa. As notas de saída suaves e frescas criam uma sensação nostálgica, enquanto o coração floral e amadeirado expressa beleza e fragilidade. A base quente e terrosa traz um toque reconfortante, ideal para aqueles que apreciam a profundidade das emoções e a beleza da tristeza.", preco: 999},
    {nome: "👑 Majesty Unveiled 👑", imagem: "https://i.imgur.com/P7e5UBk.jpeg", id: "7", nota: 4, desc: "Majesty Unveiled é uma fragrância que encapsula a força e a beleza da rainha do baralho. As notas frescas e frutadas despertam uma sensação de vivacidade, enquanto o coração floral reflete a delicadeza e a nobreza. As notas de fundo proporcionam uma profundidade rica e envolvente, tornando este perfume perfeito para a mulher que é confiante, poderosa e sofisticada.", preco: 599},
    {nome: "🃏 Laughing Chaos 🃏", imagem: "https://i.imgur.com/ubK577c.jpeg", id: "8", nota: 5, desc: "Laughing Chaos é uma fragrância explosiva e divertida que captura a essência imprevisível do Coringa. As notas cítricas e frutadas criam uma sensação vibrante, enquanto o coração floral e picante reflete sua natureza ousada. A base terrosa e doce oferece um equilíbrio intrigante, tornando este perfume ideal para quem busca expressar sua individualidade e diversão.", preco: 700},
    {nome: "❤️ Heart's Desire ❤️", imagem: "https://i.imgur.com/kmv681t.jpeg", id: "9", nota: 4, desc: "Heart's Desire significa o desejo mais profundo do coração, aquilo que alguém mais anseia ou almeja. Este perfume evoca sentimentos de paixão, aspiração e amor intenso. Baseado no naipe de copas, um perfume que busca capturar a essência dos anseios mais íntimos e sinceros, perfeito para alguém que valoriza as emoções e os desejos do coração", preco: 357}
  ]

// ⚜️​♠️​♥️​♦️​♣️​🃏​👑​😉​